-- Auto-generated schema from Bun models
-- Generated by generate_schema.go

-- Enable uuid-ossp extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(
),
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY ("id"),
  UNIQUE ("email"));

CREATE TABLE IF NOT EXISTS "posts" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(
),
  "title" varchar(500) NOT NULL,
  "user_id" uuid NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);

