name: '🐛 Bug Report'
description: 'Create a report to help us improve the project'
title: 'Bug: [Short description of the bug]'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: 'Bug Description'
      description: 'A clear and concise description of what the bug is.'
      placeholder: 'e.g., The server crashes when receiving a specific gRPC request.'
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 'Steps to Reproduce'
      description: 'Steps to reproduce the behavior. Be as specific as possible.'
      placeholder: |
        1. Start the server using `go run cmd/api/main.go`
        2. Send the following `buf curl` command...
        3. Observe the error in the server logs.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'Expected Behavior'
      description: 'A clear and concise description of what you expected to happen.'
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 'Actual Behavior'
      description: 'A clear and concise description of what actually happened.'
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: 'Environment'
      description: 'In which environment did you encounter the bug?'
      options:
        - Local (macOS)
        - Local (Windows)
        - Local (Linux/WSL)
        - Docker Compose
        - GitHub Actions (CI)
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 'Logs / Screenshots'
      description: 'If applicable, add logs, stack traces, or screenshots to help explain your problem.'
      render: shell
