blank_issues_enabled: false
contact_links:
  - name: Project README
    url: https://github.com/pannpers/go-backend-scaffold/blob/main/README.md
    about: Please check the documentation for general information before creating an issue.
